### ISSUE TITLE
An error occurred (ReportInProgress) when calling the GetCredentialReport operation

### ISSUE THREAD

**Issue by iainelder** [goldfiglabs/introspector#17]
I got an error about the IAM credential report when running an import today.

> botocore.errorfactory.CredentialReportNotReadyException: An error occurred (ReportInProgress) when calling the GetCredentialReport operation: Unknown

I understand that GenerateCredentialReport and GetCredentialReport are distinct APIs and that Introspector will have to figure out somehow when the credential report is ready.

If it fails like this, does it mean that Introspector didn't get a credential report in the end?

Is my import incomplete?

```text
$ ./introspector account aws import
[2021-03-24 19:53:38,385] {iam.py:93} ERROR - credenetial report fetch error
Traceback (most recent call last):
  File "/app/introspector/aws/iam.py", line 91, in _import_credential_report
    report = proxy.get('get_credential_report')
  File "/app/introspector/aws/fetch.py", line 404, in get
    return self._impl.get(resource, kwargs)
  File "/app/introspector/aws/fetch.py", line 131, in get
    raise e
  File "/app/introspector/aws/fetch.py", line 106, in get
    full_result = api_call(**kwargs)
  File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 676, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.CredentialReportNotReadyException: An error occurred (ReportInProgress) when calling the GetCredentialReport operation: Unknown
[2021-03-24 19:55:34,548] {resource.py:65} WARNING - Missing target for relation arn:aws:cloudwatch:us-east-1:480783779961:alarm:BillingAlert fires-on [metrics/us-east-1/None/None/] (1)
Results - Import #3
  Start:  2021-03-24 19:52:41
  End:  2021-03-24 19:55:37
  Errors:  0
  Resources added:  1
  Resources removed:  0
  Resources updated:  10
    Attributes added:  0
    Attributes removed:  0
    Attributes updated:  14
```

I'm using Docker image e934e4551c83 and release v0.1.2.

**Comment by iainelder** [comment]
During another import run I got another error about the IAM credential report.

> botocore.exceptions.ClientError: An error occurred (Throttling) when calling the GenerateCredentialReport operation (reached max retries: 4): Rate exceeded

```
$ ./introspector account aws import
[2021-03-24 21:10:35,856] {iam.py:76} ERROR - credential report error
Traceback (most recent call last):
  File "/app/introspector/aws/iam.py", line 70, in _import_credential_report
    proxy.get('generate_credential_report')
  File "/app/introspector/aws/fetch.py", line 404, in get
    return self._impl.get(resource, kwargs)
  File "/app/introspector/aws/fetch.py", line 131, in get
    raise e
  File "/app/introspector/aws/fetch.py", line 106, in get
    full_result = api_call(**kwargs)
  File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 676, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (Throttling) when calling the GenerateCredentialReport operation (reached max retries: 4): Rate exceeded
```

Adding it here as it might be related.

**Comment by gsoltis** [comment]
Your report is compete, as long as the end result says `errors: 0`. The mechanism for getting a credential report is slightly less straightforward than the rest of the API surface. This just needs to be folded into more logging cleanup, as it is part of the normal process of "Start report generation" -> "poll for report availability"

You can verify the report is included via:
```sql
SELECT
  *
FROM 
  raw_import 
WHERE 
  source = 'credentialreport' 
  AND import_job_id = <MOST RECENT IMPORT JOB>
```

**Comment by iainelder** [comment]
@gsoltis I've deleted the volume that contained the database for the reported run.

Do you want to keep this issue open to fold it into more logging cleanup?

**Comment by gsoltis** [comment]
I've just pushed a commit that should address this logging. I expect to make a release with it in the next day or so. I can close it then.

**Comment by gsoltis** [comment]
Just released. This should be fixed
